apiVersion: v1alpha1
discovery:
  jobs:
    - type: AWS/EC2
      regions:
        - ap-northeast-1
      period: 300
      length: 300
      metrics:
        - name: CPUUtilization
          statistics: [Average]
        - name: NetworkIn
          statistics: [Average, Sum]
        - name: NetworkOut
          statistics: [Average, Sum]
        